### ISSUE TITLE
ISSUE FORMATTING

### ISSUE THREAD

**Issue by Regulator13** [famegames/squared#122]
**Context:** Why I am writing this issue

**Problem or idea:** What I need fixed or what I need an idea for how to fix

**Solution or next step:** My recommendations for how to solve the problem or asking for help, including specific people when appropriate.

(More info on how to write an issue in our [wiki](https://github.com/famegames/squared/wiki/Creating-an-Issue) or [here](https://wiredcraft.com/blog/how-we-write-our-github-issues/))

**Comment by Phabbits** [comment]
I appreciate how this change will give developers more freedom, and probably make it easier for the creator of the issue, if they do not know how to code the solution. The one problem I find, is that since many of our developers are still getting used to programming in gml, it would be helpful sometime to get instructions, or step by step processes. I think that this could be done using programming question labels perhaps.

**Comment by Regulator13** [comment]
Thanks @afrey15 for the template, I'll close this now.
