### ISSUE TITLE
Health Bar 

### ISSUE THREAD

**Issue by curteckstein** [famegames/squared#129]
Context: Once the player is out of health the game fatal errors 

Problem or idea: To fix this either terminate the game once the player dies and health bar has to update or write a statement saying if HP == 0, draw so that all the green health bar is gone and only red displays 

Solution or next step: Title screen the game can exit to when a player dies or write the code statement described above

**Comment by Regulator13** [comment]
Curt! Nice addition, it was much needed. I took a look at your code, it looked good but I see where your problem is. To fix this we are going to use ` if (instance_exists())` which will check to see if there are any obj_characters left. First though, instead of using `obj_character` in your code, let's use the variable `Player`  which contains the instance id of the obj_character, but will work even if there is multiple obj_characters on the map.

Also, to save on a space, and to make this easier for when there's multiple players, you might want to move your code over to the `obj_player` event.

So here's some changes to consider for obj_healthbar code:

**Step Event**
You can delete this, the draw is like a step event, but just for drawing.

**Draw Event**
``` 
draw_sprite(spr_healthbar, 1, 50, 10);
if instance_exists(obj_player)
    draw_sprite_ext(spr_healthbar, 0, 50, 10, Player.hp * .01, 1, 0, c_white, 1);
else
    draw_sprite_ext(spr_healthbar, 0, 50, 10, 0, 1, 0, c_white, 1);
```

If you got any questions let me know. This was a pretty tough one to take on first so nice work.

**Comment by curteckstein** [comment]
I like the idea :D
The issue at hand now is that if I use Player.hp the error is that obj_player.Player is not set before being read. I am trying to find a way to set it

**Comment by Regulator13** [comment]
Yes you'll have to move the code to `obj_player`. Copy the code in your draw event into a draw event for `obj_player` and it should work, the `Player` variable is set there and won't be recognized in your other object.

**Comment by curteckstein** [comment]
Code:
Draw Event: obj_player

draw_sprite(spr_healthbar, 1, 50, 10);
if (instance_exists(obj_player) &  Player == other)
    draw_sprite_ext(spr_healthbar, 0, 50, 10, Player.hp * .01, 1, 0, c_white, 1);
else
    draw_sprite_ext(spr_healthbar, 0, 50, 10, 0, 1, 0, c_white, 1);

Issue:
For some reason Player == other is never true, and this code has to be in place because draw event happens before room start event and if the code is read without the if statement of Player == other an error will occur saying Player does not exist for Player.hp. During room start event Player = other, but it does not appear to remain equal to other for each iteration of code.

Solution Idea:
In the works

**Comment by curteckstein** [comment]
Also I had to set Player = noone in create event for obj_player

**Comment by Regulator13** [comment]
Okay, setting `Player` in the `Create Event` works. `Player == other` is never true because it is set in a `with` function so `other` actually refers to the obj_player. Do you need the `and Player == other`? The healthbar should create for the character.

**Comment by Regulator13** [comment]
Hmm, you should note that the events don't run in the order they're listed on the object. According to [this](https://docs.yoyogames.com/source/dadiospice/000_using%20gamemaker/events/index.html), the create event, and the room start event should always run first, so your draw event should know what everything is. If you're still getting an error copy in the error report and we can look at it.

**Comment by Regulator13** [comment]
Alright Curt turns out we were over-complicating this. I tried adding the code and you were right, the `Player` variable does not set in time for the draw event. However, there is a function called `draw_healthbar` that does the job for you with no sprite or object necessary. I added the code to `obj_character` in a `draw end` event, tested it, and added it to the main branch. Here is the working code in the `draw end` event.

```
/// @description Draw healthbar
draw_self();
//Draw the healthbar
draw_healthbar(32, 0, 216, 30, Player.hp, c_blue, c_red, c_green, 0, true, true);
```

If this all makes sense, you can close this issue.

**Comment by curteckstein** [comment]
Sounds like it worked and it makes sense! Only problem on my end is that I updated my code and obj_charcater is gone. But that might be another issue to open

**Comment by Regulator13** [comment]
Uh, what do you mean by gone? Like deleted?

**Comment by curteckstein** [comment]
The error that I have unmarked files happened again and I found a way to fix it I think, but, when I finally resolved it and opened squared in gml obj_charcater was gone, it seems to be deleted. Github hasn't been the nicest to me recently 😅

**Comment by Regulator13** [comment]
It sounds like it. It might be best to delete your branch (Branch>Delete) and make a new one. Update that one from the master (Branch>Update from Default) and maybe you won't have so many problems with the new one.

**Comment by curteckstein** [comment]
That's what I had to do. Also the health bar looks good so I will close this
